// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjafp_I0ToO9-nONa9_fiotPaaQ4E4ShU',
    appId: '1:394810291446:web:49b8f4388b92127493a8d7',
    messagingSenderId: '394810291446',
    projectId: 'chat-app-send-message',
    authDomain: 'chat-app-send-message.firebaseapp.com',
    storageBucket: 'chat-app-send-message.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaj-b-7AoxKFFP2i9BhTguwbLdhiLxv8Q',
    appId: '1:394810291446:android:90d1a876fd43d57c93a8d7',
    messagingSenderId: '394810291446',
    projectId: 'chat-app-send-message',
    storageBucket: 'chat-app-send-message.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_uZGn84GALMpLMUshtZaYOF52En7bqTA',
    appId: '1:394810291446:ios:44aad98ba9551bfb93a8d7',
    messagingSenderId: '394810291446',
    projectId: 'chat-app-send-message',
    storageBucket: 'chat-app-send-message.appspot.com',
    iosClientId: '394810291446-ksbniveia6qs5d4etihm8jbrp0ler2bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaskApp',
  );
}
